### ISSUE TITLE
装包后 import * as xunfei from 'xunfeisdk' 报SyntaxError: Unexpected token import异常

### ISSUE THREAD

**Issue by liaotup** [breakstring/xunfeisdk#3]
PS C:\Users\Sam\Desktop\AIUIDemo> node .\AIUI.js
C:\Users\Sam\Desktop\AIUIDemo\AIUI.js:5
import * as Xunfei from 'xunfeisdk'
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by breakstring** [comment]
呃。。。抱歉，之前我的示例和文档里没有写清楚。
目前Node不支持import语句，我的源代码包括测试用例都是用TypeScript写的，执行时执行的其实是TS生成的JS文件，它里面就没有import语句了。
如果您是使用Node来直接执行的话，要么用：
const xxx = require("xxx");
这种形式来引入，要么试试看 ts-node 来运行。

**Comment by liaotup** [comment]
对 是上述的问题  已经解决!    这个SDK封装的实在漂亮! 点个赞!

**Comment by breakstring** [comment]
多谢，对大家有用就好。 :)
